# Service Configuration
youtube:
  audio_quality: "bestaudio/best"
  output_format: "mp3"
  
audio_processing:
  silence_threshold: -40  # dB
  min_silence_duration: 2000  # ms
  
whisper:
  base_url: "http://localhost:7860"
  model: "large-v3"
  language: "en"
  
ai_formatting:
  provider: "openai"  # or "local", "anthropic"
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.3

# Output Configuration
output:
  audio_dir: "output/audio"
  transcript_dir: "output/transcripts"
  summary_dir: "output/summaries"
  keep_temp_files: false

# Service Pattern Recognition
service_patterns:
  greeting_keywords: ["good morning", "welcome", "glad to see"]
  sermon_start_keywords: ["let's turn to", "our text today", "scripture reading"]
  sermon_end_keywords: ["let's pray", "closing prayer", "benediction"]
